@baseUrl=http://localhost:3500
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTE1OTkzNzcwMzU4ZWI5MDcwNTNlMSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjc1NzEyOTE5LCJleHAiOjE2NzU3MzQ1MTl9.fJhzS3Z-I7rFBSY3xjsZBO7Iyexu9MY5jHIO2vtlT0A



# ROOT

# main
GET {{baseUrl}} HTTP/1.1

### #############################
# USER
### #############################

# Create an account.
# createUser.js

POST {{baseUrl}}/users/new HTTP/1.1
content-type: application/json

{
	"email": "admin100@myblog.net",
	"password": "Admin1234*"
}

###

# Client Login.
# login.js

POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "admin100@myblog.net",
	"password": "Admin1234*"
}

###

# PROFILE
GET {{baseUrl}}/profile/me HTTP/1.1
Authorization: Bearer {{token}}

###

# EDIT PROFILE
PUT {{baseUrl}}/profile/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"email": "admin10045@myblog.net",
	"password": "Test123fJ*"
}

###

# DELETE PROFILE
DELETE {{baseUrl}}/profile/me HTTP/1.1
Authorization: Bearer {{token}}

###
