@baseUrl=http://localhost:3500
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTU1NWUzYzQ5MDFhY2YwMzQ1NWM1YyIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjc1OTc0MTIyLCJleHAiOjE2NzU5OTU3MjJ9.Q6JQnUlHHsEgrzq-L_zJjJC9O_keNKond0EXs5-RhRw



# ROOT

# main
GET {{baseUrl}} HTTP/1.1

### #############################
# USER
### #############################

# Create an account.
# createUser.js

POST {{baseUrl}}/users/new HTTP/1.1
content-type: application/json

{
	"email": "admin100@myblog.net",
	"password": "Admin1234*"
}

###

# Client Login.
# login.js

POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "admin100@myblog.net",
	"password": "Admin1234*"
}

###

# PROFILE
GET {{baseUrl}}/profile/me HTTP/1.1
Authorization: Bearer {{token}}

###

# EDIT PROFILE
PUT {{baseUrl}}/profile/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"email": "admin10045@myblog.net",
	"password": "Test123fJ*"
}

###

# DELETE PROFILE
DELETE {{baseUrl}}/profile/me HTTP/1.1
Authorization: Bearer {{token}}

###

# POSTS

###

POST {{baseUrl}}/posts/new HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"slugg": "my first title 3",
	"body": "<h1>My title</h1><p>test paragraph</p>"
}

###

# Get post by slugg
GET {{baseUrl}}/posts/my_first_title

###

# get all posts

GET {{baseUrl}}/posts

###

# put post by slugg

PUT {{baseUrl}}/posts/my_first_title HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"body": "<h1>My title 2</h1><p>test update paragraph</p>"
}

###

DELETE {{baseUrl}}/posts/myfirsttitle HTTP/1.1
Authorization: Bearer {{token}}

###

# Comments

###

POST {{baseUrl}}/posts/my_first_title/comments/new
content-type: application/json
Authorization: Bearer {{token}}

{
	"body": "my comment"
}

###

PUT  {{baseUrl}}/posts/my_first_title/comments/63e560c3b599075a98409f0c
content-type: application/json
Authorization: Bearer {{token}}

{
	"body": "my comment update"
}

###

DELETE {{baseUrl}}/posts/my_first_title/comments/63e560e6b599075a98409f12
Authorization: Bearer {{token}}

###

# user

GET {{baseUrl}}/users
Authorization: Bearer {{token}}

GET {{baseUrl}}/users/:id
Authorization: Bearer {{token}}

