@baseUrl=http://localhost:3500
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZGY3OTRhN2IyYmQ3ZTAyNDU3MDlmYyIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY3NTU4OTk2NCwiZXhwIjoxNjc1NjExNTY0fQ.u7A_WTG3PbsjRZFPELQiht5nbcHNt0I2JVwxl7oRDY8

# ROOT

# main
GET {{baseUrl}} HTTP/1.1

### #############################
# USER
### #############################

# Create an account.
# createUser.js

POST {{baseUrl}}/users/new HTTP/1.1
content-type: application/json

{
	"email": "admin100@myblog.net",
	"password": "Admin1234*"
}

###

# Client Login.
# login.js

POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "admin@myblog.net",
	"password": "Admin1234*"
}

###

# PROFILE
GET {{baseUrl}}/profile/me HTTP/1.1
Authorization: Bearer {{token}}
